### ISSUE TITLE
Structure Problem

### ISSUE THREAD

**Issue by FlaminMad** [FlaminMad/researchProject#8]
So currently there are a variety of classes I use across all of my src projects. A classic example of this is Modbus.py
Is there a place in which i can but these so they are common to all projects (As in with the fancy new structure can i have a 'shared resources folder' or something like that)

Also, how do i then import them if they're not in the run directory?

**Comment by pet1330** [comment]
I guess I can close it as it's not needed anymore, reopen it if you still want me to take a look at it though :smiley:
